name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test stage (runs pytest)
        run: |
          docker build --target test -t aceest-fitness:test .
          docker run --rm aceest-fitness:test

      - name: Build runtime image
        run: |
          docker build --target runtime -t aceest-fitness:latest .
